import { Project } from '@/validationSchemas/project.schema'

export const Projects: Project[] = [
    {
        id: 'prj-001',
        thumbnail: 'https://www.csdvietnam.com/assets/img/logo.webp',
        sourceUrl: 'test-source',
        jobNo: 'FV.1234',
        jobName: '3D Modeling Testing',
        status: 'Delivered',
        price: '5000000',
        startedAt: new Date('2024-01-10').toString(),
        dueAt: new Date('2024-10-10').toString(),
        createdAt: new Date('2024-01-01').toString(),
        updatedAt: new Date('2024-10-11').toString(),
    },
    {
        id: 'prj-002',
        thumbnail: 'https://www.csdvietnam.com/assets/img/logo.webp',
        sourceUrl: 'test-source-2',
        jobNo: 'FV.5678',
        jobName: 'BIM Coordination',
        status: 'On Progress',
        price: '8000000',
        startedAt: new Date('2024-04-15').toString(),
        dueAt: new Date('2024-12-01').toString(),
        createdAt: new Date('2024-04-10').toString(),
        updatedAt: new Date('2024-07-01').toString(),
    },
    {
        id: 'prj-003',
        thumbnail: 'https://www.csdvietnam.com/assets/img/logo.webp',
        sourceUrl: 'test-source-3',
        jobNo: 'FV.9101',
        jobName: 'Construction Docs',
        status: 'On Progress',
        price: '3000000',
        startedAt: new Date('2024-06-01').toString(),
        dueAt: new Date('2024-11-15').toString(),
        createdAt: new Date('2024-05-25').toString(),
        updatedAt: new Date('2024-06-02').toString(),
    },
    {
        id: 'prj-004',
        thumbnail: 'https://www.csdvietnam.com/assets/img/logo.webp',
        sourceUrl: 'test-source-4',
        jobNo: 'FV.1121',
        jobName: 'Site Survey',
        status: 'Delivered',
        price: '2000000',
        startedAt: new Date('2024-02-20').toString(),
        dueAt: new Date('2024-03-15').toString(),
        createdAt: new Date('2024-02-10').toString(),
        updatedAt: new Date('2024-03-16').toString(),
    },
    {
        id: 'prj-005',
        thumbnail: 'https://www.csdvietnam.com/assets/img/logo.webp',
        sourceUrl: 'test-source-5',
        jobNo: 'FV.3141',
        jobName: 'Interior Design',
        status: 'Delivered',
        price: '10000000',
        startedAt: new Date('2024-03-01').toString(),
        dueAt: new Date('2024-09-01').toString(),
        createdAt: new Date('2024-02-25').toString(),
        updatedAt: new Date('2024-09-02').toString(),
    },
]
